version: '3.8'

services:
  api:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    container_name: minha_api_node_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
